// Nerd Font 图标码点映射（PureNerdFont / nerd-fonts v2.2.0 稳定图标）
export const NF = {
  search: '\uf002',
  user: '\uf007',
  check: '\uf00c',
  times: '\uf00d',
  star: '\uf005',
  clock: '\uf017',
  refresh: '\uf021',
  checkCircle: '\uf058',
  infoCircle: '\uf05a',
  exclamTriangle: '\uf071',
  comment: '\uf075',
  chevronRight: '\uf054',
  chevronDown: '\uf078',
  caretDown: '\uf0d7',
  link: '\uf0c1',
  listUl: '\uf0ca',
  sitemap: '\uf0e8',
  bolt: '\uf0e7',
  wrench: '\uf0ad',
  filter: '\uf0b0',
  terminal: '\uf120',
  code: '\uf121',
  codeFork: '\uf126',
  file: '\uf15b',
  database: '\uf1c0',
  trash: '\uf1f8',
  server: '\uf233',
  cogs: '\uf085',
  commentDots: '\uf4ad',
  robot: '\uf4d1',
  ghost: '\uf504',
  folderOpen: '\uf07c',
  arrowDown: '\uf063',
  arrowUp: '\uf062',
  angleDown: '\uf107',
  angleUp: '\uf106',
  angleRight: '\uf105',
  pen: '\uf304',
  play: '\uf04b',
  expand: '\uf065',
  compress: '\uf066',
  sliders: '\uf1de',
  eye: '\uf06e',
  clockRotate: '\uf1da',
  ban: '\uf05e',
};

// 参与者/类型 → 图标
export const TYPE_ICON = {
  system_prompt: NF.terminal,
  user: NF.user,
  assistant: NF.robot,
  tool: NF.wrench,
  sub_agent: NF.ghost,
  title: NF.pen,
  todo: NF.checkCircle,
  session_start: NF.play,
  session_end: NF.times,
  corrupt: NF.exclamTriangle,
  search: NF.search,
  refresh: NF.refresh,
  filter: NF.filter,
  listUl: NF.listUl,
  sitemap: NF.sitemap,
  database: NF.database,
  folderOpen: NF.folderOpen,
  clock: NF.clock,
  link: NF.link,
  codeFork: NF.codeFork,
  server: NF.server,
  commentDots: NF.commentDots,
};
